# Generated by Django 2.1.7 on 2019-02-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('barcode', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('classification_number', models.IntegerField(blank=True, default=0, null=True)),
                ('currently_issued', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_time', models.DateTimeField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=True)),
                ('mailSend', models.BooleanField(default=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lm.Book')),
            ],
        ),
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxDelayDayStudent', models.IntegerField(default=14)),
                ('maxDelayDayFaculty', models.IntegerField(default=182)),
                ('revenuePerDayStudent', models.IntegerField(default=10)),
                ('revenuePerDayFaculty', models.IntegerField(default=10)),
                ('total_Books', models.IntegerField(default=1000)),
                ('total_student', models.IntegerField(default=1000)),
                ('total_staff', models.IntegerField(default=1000)),
                ('maxBookForStudent', models.IntegerField(default=2)),
                ('maxBookForFaculty', models.IntegerField(default=3)),
                ('total_issued', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(default=' ', max_length=30)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(default='../static/lm/anon.png', upload_to='')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('payable_amount', models.IntegerField(default=0)),
                ('is_student', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exist', models.BooleanField(default=True)),
                ('bookCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lm.Student'),
        ),
    ]
