# Generated by Django 2.1.5 on 2019-02-16 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('identity', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('barcode', models.IntegerField(blank=True, default=0, null=True)),
                ('classification_number', models.IntegerField(blank=True, default=0, null=True)),
                ('currently_issued', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_time', models.DateTimeField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lm.Book')),
            ],
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxDelayDayStudent', models.IntegerField(default=14)),
                ('maxDelayDayFaculty', models.IntegerField(default=182)),
                ('revenuePerDayStudent', models.IntegerField(default=10)),
                ('revenuePerDayFaculty', models.IntegerField(default=10)),
                ('total_Books', models.IntegerField(default=1000)),
                ('total_student', models.IntegerField(default=1000)),
                ('total_staff', models.IntegerField(default=1000)),
                ('maxBookForStudent', models.IntegerField(default=2)),
                ('maxBookForFaculty', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(default=' ', max_length=30)),
                ('roll', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('image_path', models.ImageField(default='../static/lm/anon.png', upload_to='')),
                ('mobile_number', models.IntegerField(default=0)),
                ('payable_amount', models.IntegerField(default=0)),
                ('is_student', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exist', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lm.Student'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lm.Student'),
        ),
    ]
