# Generated by Django 2.1.7 on 2019-02-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarysettings',
            name='total_Books',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='librarysettings',
            name='total_staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='librarysettings',
            name='total_student',
            field=models.IntegerField(default=0),
        ),
    ]
