# Generated by Django 2.1.7 on 2019-03-01 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0002_auto_20190222_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_day',
            fields=[
                ('day', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='event_month',
            fields=[
                ('month', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='event_year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='event_month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lm.event_year'),
        ),
        migrations.AddField(
            model_name='event_day',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lm.event_month'),
        ),
    ]
