# Generated by Django 2.1.5 on 2019-02-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0003_auto_20190216_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_time', models.DateTimeField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lm.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lm.Student')),
            ],
        ),
    ]
