# Generated by Django 2.1.7 on 2019-03-01 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0003_auto_20190301_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lm.event_day'),
        ),
    ]
