# Generated by Django 2.1.5 on 2019-02-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0004_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
