# Generated by Django 2.1.7 on 2019-03-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0004_issue_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
