# Generated by Django 2.1.5 on 2019-02-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0005_remove_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bookCount',
            field=models.IntegerField(default=0),
        ),
    ]
