# Generated by Django 2.1.5 on 2019-02-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0006_student_bookcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='mailSend',
            field=models.BooleanField(default=False),
        ),
    ]
