# Generated by Django 2.1.5 on 2019-02-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0009_auto_20190216_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_late',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
