# Generated by Django 2.1.5 on 2019-02-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0010_auto_20190216_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lm.Book'),
        ),
    ]
