# Generated by Django 2.1.5 on 2019-02-17 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0011_auto_20190217_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lm.Book'),
        ),
    ]
